---
title: "Práctica 2: Limpieza y análisis de datos"
author: "Pedro Uceda Martínez, Pablo Campillo Sánchez"
date: '`r format(Sys.Date(),"%e de %B, %Y")`'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. Descripción del dataset

Durante esta práctica vamos a tratar el _dataset_ base de la competición [**Titanic - Machine Learning from Disaster**](https://www.kaggle.com/c/titanic/overview). En este conjunto de datos se nos presenta, para cada pasajero del tan famoso trasatlántico, sus datos personales más importantes, así como otros relacionados con su embarque en el Titanic, y si finalmente sobrevivieron al naufragio del mismo.

De este modo, este estudio es interesante dado que examinaremos qué posibles factores pudieron influir en la supervivencia de los pasajeros. Así, podremos, por ejemplo, ver si solamente la clase del billete el género (mujeres) y la edad (niños) condicionaron que un viajero se salvase tal y como hemos visto en la gran pantalla o bien hubiera habido otros factores que pudieran haber determinado la supervivencia del pasajero, como el número de billete.

Las variables de las que disponemos, para cada pasajero, son:

- **survival**: Si sobrevivió (1) o no (0).
- **pclass**: Clase del pasaje. 
- **sex**: Sexo del viajero.
- **Age**: Edad, en años.
- **sibsp**: Número de hermanos o esposas a bordo del Titanic
- **parch**: Número de padres / hijos a bordo del Titanic
- **ticket**: Número de ticket
- **fare**: Tarifa del pasaje
- **cabin**: Número de camarote
- **embarked**: Puerto desde el que embarcó el pasajero. Las posibles opciones son: Cherbourg(C), Queenstown(Q) o Southampton(s).

